package studio.guitarlab.core.separation
import org.junit.Assert.*
import org.junit.Test
import java.util.UUID
import kotlinx.coroutines.runBlocking
class RemoteSeparationTest {
 private fun id()=RemoteJobIdentity(UUID.randomUUID().toString(),"project-1","source-1","a".repeat(64))
 @Test fun terminalStatesNeverRegress(){assertFalse(RemoteStateMachine.accepts(RemoteJobState.IMPORTED,RemoteJobState.RUNNING));assertFalse(RemoteStateMachine.accepts(RemoteJobState.FAILED,RemoteJobState.QUEUED));assertTrue(RemoteStateMachine.accepts(RemoteJobState.RUNNING,RemoteJobState.COMPLETED))}
 @Test fun sixStemContractIsPinned(){val i=id();val s=RemoteResultManifest.STEMS.map{RemoteStem(it,"remote/v1/output/"+it+".wav",45,"b".repeat(64))};RemoteResultManifest(i.jobId,i.projectId,i.inputSha256,"demucs.cpp","rc5","htdemucs_6s",RemoteResultManifest.MODEL_SHA256,44100,2,44100,1.0,s).validateFor(i)}
 @Test fun ownershipFailsClosed(){val i=id();val s=RemoteResultManifest.STEMS.map{RemoteStem(it,"remote/v1/output/"+it+".wav",45,"b".repeat(64))};val m=RemoteResultManifest(i.jobId,"other",i.inputSha256,"demucs.cpp","rc5","htdemucs_6s",RemoteResultManifest.MODEL_SHA256,44100,2,1,1.0,s);assertThrows(IllegalArgumentException::class.java){m.validateFor(i)}}
 @Test fun retryPolicyProtectsIntegrity(){assertFalse(RemoteFailurePolicy.shouldRetry("INPUT_HASH_MISMATCH",0));assertFalse(RemoteFailurePolicy.shouldRetry("QUOTA_EXCEEDED",0));assertTrue(RemoteFailurePolicy.shouldRetry("BACKEND_UNAVAILABLE",0))}
 @Test fun cancelRequestedCanOnlyReachARealTerminalState(){assertTrue(RemoteStateMachine.accepts(RemoteJobState.CANCEL_REQUESTED,RemoteJobState.CANCELLED));assertTrue(RemoteStateMachine.accepts(RemoteJobState.CANCEL_REQUESTED,RemoteJobState.COMPLETED));assertFalse(RemoteStateMachine.accepts(RemoteJobState.CANCEL_REQUESTED,RemoteJobState.RUNNING))}
 @Test fun everyManifestInvariantFailsClosed(){
  val i=id();fun valid()=RemoteResultManifest(i.jobId,i.projectId,i.inputSha256,"demucs.cpp","rc5","htdemucs_6s",RemoteResultManifest.MODEL_SHA256,44100,2,44100,1.0,RemoteResultManifest.STEMS.map{RemoteStem(it,"remote/v1/output/$it.wav",45,"b".repeat(64))})
  val invalid=listOf(
   valid().copy(jobId=UUID.randomUUID().toString()),valid().copy(projectId="wrong"),valid().copy(inputSha256="c".repeat(64)),
   valid().copy(engine="wrong"),valid().copy(model="wrong"),valid().copy(modelSha256="c".repeat(64)),valid().copy(sampleRate=48000),valid().copy(channels=1),
   valid().copy(frames=0),valid().copy(durationSeconds=0.0),valid().copy(stems=valid().stems.dropLast(1)),
   valid().copy(stems=valid().stems+RemoteStem("extra","remote/v1/output/extra.wav",45,"b".repeat(64))),
   valid().copy(stems=valid().stems.dropLast(1)+valid().stems.first()),valid().copy(stems=valid().stems.mapIndexed{n,s->if(n==0)s.copy(bytes=0) else s}),
   valid().copy(stems=valid().stems.mapIndexed{n,s->if(n==0)s.copy(sha256="bad") else s}),valid().copy(stems=valid().stems.mapIndexed{n,s->if(n==0)s.copy(path="../escape.wav") else s})
  )
  invalid.forEach{m->assertThrows(IllegalArgumentException::class.java){m.validateFor(i)}}
 }
 @Test fun cancelRequestedWithoutRemoteTerminalizesLocally()=runBlocking{
  val i=id();val events=mutableListOf<String>();val store=MemoryStore(DurableRemoteJob(i,RemoteJobState.CANCEL_REQUESTED,1));val backend=object:RemoteSeparationBackend{override suspend fun enqueue(identity:RemoteJobIdentity,inputPath:String){events+="enqueue"};override suspend fun status(identity:RemoteJobIdentity):DurableRemoteJob?=null;override suspend fun cancel(identity:RemoteJobIdentity){events+="cancel"};override suspend fun acknowledge(identity:RemoteJobIdentity,resultManifestSha256:String){}};val transport=object:RemoteResultTransport{override suspend fun uploadSource(identity:RemoteJobIdentity):String{events+="upload";return "input"};override suspend fun downloadManifest(identity:RemoteJobIdentity)=error("unused");override suspend fun downloadStem(identity:RemoteJobIdentity,stem:RemoteStem)=error("unused");override suspend fun cleanup(identity:RemoteJobIdentity){}};val publisher=object:RemoteStemPublisher{override fun publish(identity:RemoteJobIdentity,manifest:RemoteResultManifest,manifestSha256:String,stems:Map<String,ByteArray>)=true};val result=RemoteSeparationCoordinator(store,backend,transport,{error("unused")},publisher).reconcile(i);assertTrue(events.isEmpty());assertEquals(RemoteJobState.CANCELLED,result.state);assertEquals(RemoteMissingPolicy.ERROR_REMOTE_JOB_NOT_FOUND,result.errorCode)
 }
 @Test fun runningWithoutRemoteExpiresInsteadOfRemainingActive()=runBlocking{
  val i=id();val store=MemoryStore(DurableRemoteJob(i,RemoteJobState.RUNNING,1));val backend=object:RemoteSeparationBackend{override suspend fun enqueue(identity:RemoteJobIdentity,inputPath:String){};override suspend fun status(identity:RemoteJobIdentity):DurableRemoteJob?=null;override suspend fun cancel(identity:RemoteJobIdentity){};override suspend fun acknowledge(identity:RemoteJobIdentity,resultManifestSha256:String){}};val transport=object:RemoteResultTransport{override suspend fun uploadSource(identity:RemoteJobIdentity)="unused";override suspend fun downloadManifest(identity:RemoteJobIdentity)=error("unused");override suspend fun downloadStem(identity:RemoteJobIdentity,stem:RemoteStem)=error("unused");override suspend fun cleanup(identity:RemoteJobIdentity){}};val publisher=object:RemoteStemPublisher{override fun publish(identity:RemoteJobIdentity,manifest:RemoteResultManifest,manifestSha256:String,stems:Map<String,ByteArray>)=true};val result=RemoteSeparationCoordinator(store,backend,transport,{error("unused")},publisher).reconcile(i);assertEquals(RemoteJobState.EXPIRED,result.state);assertEquals(RemoteMissingPolicy.ERROR_REMOTE_JOB_NOT_FOUND,result.errorCode)
 }
 @Test fun completedAndImportingWithoutRemoteExpireSafely(){assertEquals(RemoteJobState.EXPIRED,RemoteMissingPolicy.terminalState(RemoteJobState.COMPLETED));assertEquals(RemoteJobState.EXPIRED,RemoteMissingPolicy.terminalState(RemoteJobState.IMPORTING))}
 @Test fun missingRemoteJobReplaysUploadAndEnqueueIdempotently()=runBlocking{
  val i=id();val events=mutableListOf<String>();val store=MemoryStore(DurableRemoteJob(i,RemoteJobState.READY,1));val backend=object:RemoteSeparationBackend{override suspend fun enqueue(identity:RemoteJobIdentity,inputPath:String){events+="enqueue:$inputPath"};override suspend fun status(identity:RemoteJobIdentity):DurableRemoteJob?=null;override suspend fun cancel(identity:RemoteJobIdentity){};override suspend fun acknowledge(identity:RemoteJobIdentity,resultManifestSha256:String){}};val transport=object:RemoteResultTransport{override suspend fun uploadSource(identity:RemoteJobIdentity):String{events+="upload";return "owned/input"};override suspend fun downloadManifest(identity:RemoteJobIdentity)=error("unused");override suspend fun downloadStem(identity:RemoteJobIdentity,stem:RemoteStem)=error("unused");override suspend fun cleanup(identity:RemoteJobIdentity){}};val publisher=object:RemoteStemPublisher{override fun publish(identity:RemoteJobIdentity,manifest:RemoteResultManifest,manifestSha256:String,stems:Map<String,ByteArray>)=true};val result=RemoteSeparationCoordinator(store,backend,transport,{error("unused")},publisher).reconcile(i);assertEquals(listOf("upload","enqueue:owned/input"),events);assertEquals(RemoteJobState.QUEUED,result.state)
 }
 @Test fun ackHappensOnlyAfterDurablePublication()=runBlocking {
  val i=id();val bytes="manifest".toByteArray();val hash=java.security.MessageDigest.getInstance("SHA-256").digest(bytes).joinToString(""){"%02x".format(it)};val stems=RemoteResultManifest.STEMS.map{RemoteStem(it,"remote/v1/output/$it.wav",45,"b".repeat(64))};val manifest=RemoteResultManifest(i.jobId,i.projectId,i.inputSha256,"demucs.cpp","rc5","htdemucs_6s",RemoteResultManifest.MODEL_SHA256,44100,2,1,1.0,stems);val events=mutableListOf<String>();val store=MemoryStore(DurableRemoteJob(i,RemoteJobState.RUNNING,1));val backend=object:RemoteSeparationBackend{override suspend fun enqueue(identity:RemoteJobIdentity,inputPath:String){};override suspend fun status(identity:RemoteJobIdentity)=DurableRemoteJob(i,RemoteJobState.COMPLETED,2,hash);override suspend fun cancel(identity:RemoteJobIdentity){};override suspend fun acknowledge(identity:RemoteJobIdentity,resultManifestSha256:String){events+="ack"}};val transport=object:RemoteResultTransport{override suspend fun uploadSource(identity:RemoteJobIdentity)="input";override suspend fun downloadManifest(identity:RemoteJobIdentity)=bytes;override suspend fun downloadStem(identity:RemoteJobIdentity,stem:RemoteStem)=ByteArray(45);override suspend fun cleanup(identity:RemoteJobIdentity){events+="cleanup"}};val publisher=object:RemoteStemPublisher{override fun publish(identity:RemoteJobIdentity,manifest:RemoteResultManifest,manifestSha256:String,stems:Map<String,ByteArray>):Boolean{events+="publish";return false}};RemoteSeparationCoordinator(store,backend,transport,{manifest},publisher).reconcile(i);assertEquals(listOf("publish","ack","cleanup"),events);assertEquals(RemoteJobState.IMPORTED,store.job.state)
 }
 private class MemoryStore(var job:DurableRemoteJob):RemoteJobStore{override fun load(jobId:String)=job;override fun save(job:DurableRemoteJob):DurableRemoteJob{if(RemoteStateMachine.accepts(this.job.state,job.state))this.job=job;return this.job}}
}
